server:
  port: 9083
  
logging:
  path: c:\dev\logs
  file: porkerspicks.log
  level:
    root: WARN 
    com:
      porkerspicks: debug
    org: 
      springframework:
        security: debug